package es.tearain.jampeep.model;

public enum Service {
	YOUTUBE, GOOGLE, STEAM, FACEBOOK, AMAZON, TWITTER, 
	LIVE, INSTAGRAM, MARCA, MILANUNCIOS, EBAY, LINKEDIN, 
	IDEALISTA, PINTEREST, FOROCOCHES, INFOJOBS, NETFLIX, 
	HBO, PAYPAL, ALIEXPRESS, BOOKING, YAHOO, DROPBOX;
}
